### PR TITLE
Fix site build for Roslyn's master branch

### PR DESCRIPTION
**Pull request by controlflow**
Roslyn's `master` branch build of TryRoslyn is not updating since October 30 :(
Fixed a pair of issues I've found...

### CODE REVIEW

**Comment by ashmind** [comment]
@controlflow Thanks a lot! After some research, I decided to take a different approach with "!" — don't want to give up my naming due to their bugs. But your solution was perfectly valid.

**Comment by controlflow** [comment]
@ashmind have you deployed the fix to http://tryroslyn.azurewebsites.net? I see branch info updated, but it looks like the Roslyn version is outdated. For example, this compiles fine with `master` branch csc.exe and produces error on http://tryroslyn.azurewebsites.net:

```c#
using System;
public class C {
    public void M() {
        Action a = () => throw null;
    }
}
```

http://tryroslyn.azurewebsites.net/#b:master/K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbGNmfYsmANwHswAExgBZABQBKZq3ayAgqWRg+EGFRgBeGJM0A+GMgAWAJz4B3GBGBEiOWQF9s9oA

I can't reproduce this with locally-build tryroslyn, let me know if I can help diagnose the problem somehow

**Comment by ashmind** [comment]
@controlflow Yes it should be deployed, but maybe I messed up something. Unfortunately I can only check it in the evening (in 11 hrs or so) — I'll let you know.

**Comment by ashmind** [comment]
@controlflow OK it was broken pretty thoroughly, and was picking up old files.  
Full rebuild would probably take an hour or more, after that I would expect your example to be fixed.

**Comment by ashmind** [comment]
@controlflow Found another issue.
I don't have any more time, so I fixed it manually for now and disabled the builds.

I'll do a proper fix over the weekend.

**Comment by ashmind** [comment]
@controlflow OK builds should be reliable now.

**Pull request merged**
